version: '3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    container_name: python-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "8080:5000"  # Exponer el puerto 5000 del contenedor en el host en el puerto 8080
    command: tail -f /dev/null
